// AUTO-GENERATED by scripts/generate-ai-skill-manifest.mjs — DO NOT EDIT.
// Run `npm run ai:sync-skills` after adding or removing a skill file.
// `npm run build` regenerates this automatically.

import type { Skill } from '@/lib/ai/types'
import { default as assign_designer } from '@/lib/ai/skills/assign-designer'
import { default as client_update_draft } from '@/lib/ai/skills/client-update-draft'
import { default as compose_newsletter } from '@/lib/ai/skills/compose-newsletter'
import { default as create_design_request } from '@/lib/ai/skills/create-design-request'
import { default as create_ticket } from '@/lib/ai/skills/create-ticket'
import { default as dashboard_stats } from '@/lib/ai/skills/dashboard-stats'
import { default as enrich_from_salesforce } from '@/lib/ai/skills/enrich-from-salesforce'
import { default as generate_signage_proof } from '@/lib/ai/skills/generate-signage-proof'
import { default as jireh_repeat_clients_report } from '@/lib/ai/skills/jireh-repeat-clients-report'
import { default as log_maintenance } from '@/lib/ai/skills/log-maintenance'
import { default as log_walkthrough } from '@/lib/ai/skills/log-walkthrough'
import { default as morning_command_center } from '@/lib/ai/skills/morning-command-center'
import { default as move_design_to_client_review } from '@/lib/ai/skills/move-design-to-client-review'
import { default as operations_snapshot } from '@/lib/ai/skills/operations-snapshot'
import { default as ops_count_records } from '@/lib/ai/skills/ops-count-records'
import { default as ops_create_row } from '@/lib/ai/skills/ops-create-row'
import { default as ops_delete_records } from '@/lib/ai/skills/ops-delete-records'
import { default as ops_list_documents } from '@/lib/ai/skills/ops-list-documents'
import { default as ops_list_tables } from '@/lib/ai/skills/ops-list-tables'
import { default as ops_query_table } from '@/lib/ai/skills/ops-query-table'
import { default as ops_table_schema } from '@/lib/ai/skills/ops-table-schema'
import { default as ops_update_records } from '@/lib/ai/skills/ops-update-records'
import { default as ops_write_document } from '@/lib/ai/skills/ops-write-document'
import { default as project_schedule_workspace } from '@/lib/ai/skills/project-schedule-workspace'
import { default as search_design_requests } from '@/lib/ai/skills/search-design-requests'
import { default as search_events } from '@/lib/ai/skills/search-events'
import { default as search_staff } from '@/lib/ai/skills/search-staff'
import { default as search_venues } from '@/lib/ai/skills/search-venues'
import { default as slack_create_canvas } from '@/lib/ai/skills/slack-create-canvas'
import { default as staffing_recommendations } from '@/lib/ai/skills/staffing-recommendations'
import { default as ticket_context } from '@/lib/ai/skills/ticket-context'
import { default as triage_request, skills as triage_request_skills } from '@/lib/ai/skills/triage-request'
import { default as update_design } from '@/lib/ai/skills/update-design'
import { default as update_ticket } from '@/lib/ai/skills/update-ticket'
import { default as venue_health_report } from '@/lib/ai/skills/venue-health-report'

/** Every skill defined by a file in lib/ai/skills/. */
export const fileSkills: Skill[] = [
  assign_designer,
  client_update_draft,
  compose_newsletter,
  create_design_request,
  create_ticket,
  dashboard_stats,
  enrich_from_salesforce,
  generate_signage_proof,
  jireh_repeat_clients_report,
  log_maintenance,
  log_walkthrough,
  morning_command_center,
  move_design_to_client_review,
  operations_snapshot,
  ops_count_records,
  ops_create_row,
  ops_delete_records,
  ops_list_documents,
  ops_list_tables,
  ops_query_table,
  ops_table_schema,
  ops_update_records,
  ops_write_document,
  project_schedule_workspace,
  search_design_requests,
  search_events,
  search_staff,
  search_venues,
  slack_create_canvas,
  staffing_recommendations,
  ticket_context,
  triage_request,
  ...triage_request_skills,
  update_design,
  update_ticket,
  venue_health_report,
]

/** Filenames this manifest was generated from — used by the staleness check. */
export const manifestFiles: string[] = [
  'assign-designer',
  'client-update-draft',
  'compose-newsletter',
  'create-design-request',
  'create-ticket',
  'dashboard-stats',
  'enrich-from-salesforce',
  'generate-signage-proof',
  'jireh-repeat-clients-report',
  'log-maintenance',
  'log-walkthrough',
  'morning-command-center',
  'move-design-to-client-review',
  'operations-snapshot',
  'ops-count-records',
  'ops-create-row',
  'ops-delete-records',
  'ops-list-documents',
  'ops-list-tables',
  'ops-query-table',
  'ops-table-schema',
  'ops-update-records',
  'ops-write-document',
  'project-schedule-workspace',
  'search-design-requests',
  'search-events',
  'search-staff',
  'search-venues',
  'slack-create-canvas',
  'staffing-recommendations',
  'ticket-context',
  'triage-request',
  'update-design',
  'update-ticket',
  'venue-health-report',
]
