/**
 * Venue walk-thru checklists — Joe 2026-08-17.
 *
 * "Would like to develop a way to create venue specific walk-thru check lists.
 *  Name of employee performing the walk-thru (can be assigned by a manager just
 *  like an event). Ability to add screens, systems, custom fields per venue
 *  (once created it should become the standard walk for the venue, but can be
 *  edited if screens get added, removed etc). Once the screens and systems are
 *  added the employee should be able to click 'Operating as intended' or
 *  'Issue found'. If 'Issue Found' is selected, they should have to add detail
 *  in a text field. Once a walk-thru is submitted a summary gets received by
 *  the same emails in the ticket system. If any issues were found, a ticket
 *  gets autogenerated with the issues outlined."
 *
 * Three tables, mirroring the three nouns in that ask:
 *   - a TEMPLATE per venue (the standard walk)
 *   - an assigned INSTANCE of that walk for one person on one date
 *   - one RESULT row per checklist item on that instance
 *
 * The existing free-text `walkthrough_logs` table is untouched. It records a
 * different thing (a visit happened, here are notes) and is still written by
 * the ops data tables. This is the structured, per-screen checklist Joe asked
 * for, and the two coexist.
 *
 * Item labels are SNAPSHOTTED onto the result rows. A venue that removes a
 * screen next season must not rewrite what a technician reported last season.
 */
import { query } from '../lib/db'

async function main() {
  await query(`
    CREATE TABLE IF NOT EXISTS venue_walkthrough_templates (
      id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
      venue_id uuid NOT NULL REFERENCES venues(id) ON DELETE CASCADE,
      name text NOT NULL DEFAULT 'Standard Walk-Thru',
      is_active boolean NOT NULL DEFAULT true,
      created_by uuid REFERENCES staff(id),
      created_at timestamptz NOT NULL DEFAULT now(),
      updated_at timestamptz NOT NULL DEFAULT now(),
      -- One standard walk per venue. "Once created it should become the
      -- standard walk for the venue" — so the venue, not the template, is the
      -- identity, and edits mutate this row rather than forking a second list.
      UNIQUE (venue_id)
    );
  `)

  await query(`
    CREATE TABLE IF NOT EXISTS venue_walkthrough_template_items (
      id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
      template_id uuid NOT NULL REFERENCES venue_walkthrough_templates(id) ON DELETE CASCADE,
      label text NOT NULL,
      item_type text NOT NULL DEFAULT 'screen',
      help_text text,
      position integer NOT NULL DEFAULT 0,
      is_active boolean NOT NULL DEFAULT true,
      created_at timestamptz NOT NULL DEFAULT now(),
      updated_at timestamptz NOT NULL DEFAULT now(),
      CONSTRAINT venue_walkthrough_item_type_check
        CHECK (item_type IN ('screen', 'system', 'custom'))
    );
    CREATE INDEX IF NOT EXISTS idx_walkthrough_template_items_template
      ON venue_walkthrough_template_items(template_id, position);
  `)

  await query(`
    CREATE TABLE IF NOT EXISTS venue_walkthroughs (
      id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
      venue_id uuid NOT NULL REFERENCES venues(id) ON DELETE CASCADE,
      template_id uuid REFERENCES venue_walkthrough_templates(id) ON DELETE SET NULL,
      assigned_staff_id uuid REFERENCES staff(id),
      assigned_by uuid REFERENCES staff(id),
      scheduled_for date,
      status text NOT NULL DEFAULT 'assigned',
      submitted_at timestamptz,
      submitted_by uuid REFERENCES staff(id),
      summary_sent_at timestamptz,
      summary_recipients text[],
      generated_ticket_id uuid REFERENCES tickets(id) ON DELETE SET NULL,
      notes text,
      created_at timestamptz NOT NULL DEFAULT now(),
      updated_at timestamptz NOT NULL DEFAULT now(),
      CONSTRAINT venue_walkthrough_status_check
        CHECK (status IN ('assigned', 'in_progress', 'submitted', 'cancelled'))
    );
    CREATE INDEX IF NOT EXISTS idx_venue_walkthroughs_venue
      ON venue_walkthroughs(venue_id, scheduled_for DESC);
    CREATE INDEX IF NOT EXISTS idx_venue_walkthroughs_assignee
      ON venue_walkthroughs(assigned_staff_id, status);
  `)

  await query(`
    CREATE TABLE IF NOT EXISTS venue_walkthrough_results (
      id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
      walkthrough_id uuid NOT NULL REFERENCES venue_walkthroughs(id) ON DELETE CASCADE,
      template_item_id uuid REFERENCES venue_walkthrough_template_items(id) ON DELETE SET NULL,
      -- Snapshot of the item as it read on the day, so later template edits
      -- cannot rewrite history.
      label text NOT NULL,
      item_type text NOT NULL DEFAULT 'screen',
      position integer NOT NULL DEFAULT 0,
      result text,
      detail text,
      created_at timestamptz NOT NULL DEFAULT now(),
      updated_at timestamptz NOT NULL DEFAULT now(),
      CONSTRAINT venue_walkthrough_result_check
        CHECK (result IS NULL OR result IN ('operating', 'issue')),
      -- "If Issue Found is selected, they should have to add detail" — enforced
      -- in the database, not only in the form, so no API path can bypass it.
      CONSTRAINT venue_walkthrough_issue_needs_detail
        CHECK (result <> 'issue' OR (detail IS NOT NULL AND length(btrim(detail)) > 0)),
      UNIQUE (walkthrough_id, template_item_id)
    );
    CREATE INDEX IF NOT EXISTS idx_venue_walkthrough_results_walkthrough
      ON venue_walkthrough_results(walkthrough_id, position);
  `)

  console.log('Venue walk-thru checklist tables ready')
  process.exit(0)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
